// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// HostSgroup is an object representing the database table.
type HostSgroup struct {
	HostID   int64 `boil:"host_id" json:"host_id" toml:"host_id" yaml:"host_id"`
	SgroupID int64 `boil:"sgroup_id" json:"sgroup_id" toml:"sgroup_id" yaml:"sgroup_id"`

	R *hostSgroupR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L hostSgroupL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var HostSgroupColumns = struct {
	HostID   string
	SgroupID string
}{
	HostID:   "host_id",
	SgroupID: "sgroup_id",
}

var HostSgroupTableColumns = struct {
	HostID   string
	SgroupID string
}{
	HostID:   "host_sgroup.host_id",
	SgroupID: "host_sgroup.sgroup_id",
}

// Generated where

var HostSgroupWhere = struct {
	HostID   whereHelperint64
	SgroupID whereHelperint64
}{
	HostID:   whereHelperint64{field: "\"host_sgroup\".\"host_id\""},
	SgroupID: whereHelperint64{field: "\"host_sgroup\".\"sgroup_id\""},
}

// HostSgroupRels is where relationship names are stored.
var HostSgroupRels = struct {
}{}

// hostSgroupR is where relationships are stored.
type hostSgroupR struct {
}

// NewStruct creates a new relationship struct
func (*hostSgroupR) NewStruct() *hostSgroupR {
	return &hostSgroupR{}
}

// hostSgroupL is where Load methods for each relationship are stored.
type hostSgroupL struct{}

var (
	hostSgroupAllColumns            = []string{"host_id", "sgroup_id"}
	hostSgroupColumnsWithoutDefault = []string{"host_id", "sgroup_id"}
	hostSgroupColumnsWithDefault    = []string{}
	hostSgroupPrimaryKeyColumns     = []string{"host_id", "sgroup_id"}
	hostSgroupGeneratedColumns      = []string{}
)

type (
	// HostSgroupSlice is an alias for a slice of pointers to HostSgroup.
	// This should almost always be used instead of []HostSgroup.
	HostSgroupSlice []*HostSgroup
	// HostSgroupHook is the signature for custom HostSgroup hook methods
	HostSgroupHook func(context.Context, boil.ContextExecutor, *HostSgroup) error

	hostSgroupQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	hostSgroupType                 = reflect.TypeOf(&HostSgroup{})
	hostSgroupMapping              = queries.MakeStructMapping(hostSgroupType)
	hostSgroupPrimaryKeyMapping, _ = queries.BindMapping(hostSgroupType, hostSgroupMapping, hostSgroupPrimaryKeyColumns)
	hostSgroupInsertCacheMut       sync.RWMutex
	hostSgroupInsertCache          = make(map[string]insertCache)
	hostSgroupUpdateCacheMut       sync.RWMutex
	hostSgroupUpdateCache          = make(map[string]updateCache)
	hostSgroupUpsertCacheMut       sync.RWMutex
	hostSgroupUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var hostSgroupAfterSelectHooks []HostSgroupHook

var hostSgroupBeforeInsertHooks []HostSgroupHook
var hostSgroupAfterInsertHooks []HostSgroupHook

var hostSgroupBeforeUpdateHooks []HostSgroupHook
var hostSgroupAfterUpdateHooks []HostSgroupHook

var hostSgroupBeforeDeleteHooks []HostSgroupHook
var hostSgroupAfterDeleteHooks []HostSgroupHook

var hostSgroupBeforeUpsertHooks []HostSgroupHook
var hostSgroupAfterUpsertHooks []HostSgroupHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *HostSgroup) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range hostSgroupAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *HostSgroup) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range hostSgroupBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *HostSgroup) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range hostSgroupAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *HostSgroup) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range hostSgroupBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *HostSgroup) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range hostSgroupAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *HostSgroup) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range hostSgroupBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *HostSgroup) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range hostSgroupAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *HostSgroup) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range hostSgroupBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *HostSgroup) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range hostSgroupAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddHostSgroupHook registers your hook function for all future operations.
func AddHostSgroupHook(hookPoint boil.HookPoint, hostSgroupHook HostSgroupHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		hostSgroupAfterSelectHooks = append(hostSgroupAfterSelectHooks, hostSgroupHook)
	case boil.BeforeInsertHook:
		hostSgroupBeforeInsertHooks = append(hostSgroupBeforeInsertHooks, hostSgroupHook)
	case boil.AfterInsertHook:
		hostSgroupAfterInsertHooks = append(hostSgroupAfterInsertHooks, hostSgroupHook)
	case boil.BeforeUpdateHook:
		hostSgroupBeforeUpdateHooks = append(hostSgroupBeforeUpdateHooks, hostSgroupHook)
	case boil.AfterUpdateHook:
		hostSgroupAfterUpdateHooks = append(hostSgroupAfterUpdateHooks, hostSgroupHook)
	case boil.BeforeDeleteHook:
		hostSgroupBeforeDeleteHooks = append(hostSgroupBeforeDeleteHooks, hostSgroupHook)
	case boil.AfterDeleteHook:
		hostSgroupAfterDeleteHooks = append(hostSgroupAfterDeleteHooks, hostSgroupHook)
	case boil.BeforeUpsertHook:
		hostSgroupBeforeUpsertHooks = append(hostSgroupBeforeUpsertHooks, hostSgroupHook)
	case boil.AfterUpsertHook:
		hostSgroupAfterUpsertHooks = append(hostSgroupAfterUpsertHooks, hostSgroupHook)
	}
}

// One returns a single hostSgroup record from the query.
func (q hostSgroupQuery) One(ctx context.Context, exec boil.ContextExecutor) (*HostSgroup, error) {
	o := &HostSgroup{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for host_sgroup")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all HostSgroup records from the query.
func (q hostSgroupQuery) All(ctx context.Context, exec boil.ContextExecutor) (HostSgroupSlice, error) {
	var o []*HostSgroup

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to HostSgroup slice")
	}

	if len(hostSgroupAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all HostSgroup records in the query.
func (q hostSgroupQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count host_sgroup rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q hostSgroupQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if host_sgroup exists")
	}

	return count > 0, nil
}

// HostSgroups retrieves all the records using an executor.
func HostSgroups(mods ...qm.QueryMod) hostSgroupQuery {
	mods = append(mods, qm.From("\"host_sgroup\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"host_sgroup\".*"})
	}

	return hostSgroupQuery{q}
}

// FindHostSgroup retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindHostSgroup(ctx context.Context, exec boil.ContextExecutor, hostID int64, sgroupID int64, selectCols ...string) (*HostSgroup, error) {
	hostSgroupObj := &HostSgroup{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"host_sgroup\" where \"host_id\"=? AND \"sgroup_id\"=?", sel,
	)

	q := queries.Raw(query, hostID, sgroupID)

	err := q.Bind(ctx, exec, hostSgroupObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from host_sgroup")
	}

	if err = hostSgroupObj.doAfterSelectHooks(ctx, exec); err != nil {
		return hostSgroupObj, err
	}

	return hostSgroupObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *HostSgroup) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no host_sgroup provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(hostSgroupColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	hostSgroupInsertCacheMut.RLock()
	cache, cached := hostSgroupInsertCache[key]
	hostSgroupInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			hostSgroupAllColumns,
			hostSgroupColumnsWithDefault,
			hostSgroupColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(hostSgroupType, hostSgroupMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(hostSgroupType, hostSgroupMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"host_sgroup\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"host_sgroup\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into host_sgroup")
	}

	if !cached {
		hostSgroupInsertCacheMut.Lock()
		hostSgroupInsertCache[key] = cache
		hostSgroupInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the HostSgroup.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *HostSgroup) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	hostSgroupUpdateCacheMut.RLock()
	cache, cached := hostSgroupUpdateCache[key]
	hostSgroupUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			hostSgroupAllColumns,
			hostSgroupPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update host_sgroup, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"host_sgroup\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, hostSgroupPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(hostSgroupType, hostSgroupMapping, append(wl, hostSgroupPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update host_sgroup row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for host_sgroup")
	}

	if !cached {
		hostSgroupUpdateCacheMut.Lock()
		hostSgroupUpdateCache[key] = cache
		hostSgroupUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q hostSgroupQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for host_sgroup")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for host_sgroup")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o HostSgroupSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), hostSgroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"host_sgroup\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, hostSgroupPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in hostSgroup slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all hostSgroup")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *HostSgroup) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no host_sgroup provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(hostSgroupColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	hostSgroupUpsertCacheMut.RLock()
	cache, cached := hostSgroupUpsertCache[key]
	hostSgroupUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			hostSgroupAllColumns,
			hostSgroupColumnsWithDefault,
			hostSgroupColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			hostSgroupAllColumns,
			hostSgroupPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert host_sgroup, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(hostSgroupPrimaryKeyColumns))
			copy(conflict, hostSgroupPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"host_sgroup\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(hostSgroupType, hostSgroupMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(hostSgroupType, hostSgroupMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert host_sgroup")
	}

	if !cached {
		hostSgroupUpsertCacheMut.Lock()
		hostSgroupUpsertCache[key] = cache
		hostSgroupUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single HostSgroup record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *HostSgroup) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no HostSgroup provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), hostSgroupPrimaryKeyMapping)
	sql := "DELETE FROM \"host_sgroup\" WHERE \"host_id\"=? AND \"sgroup_id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from host_sgroup")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for host_sgroup")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q hostSgroupQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no hostSgroupQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from host_sgroup")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for host_sgroup")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o HostSgroupSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(hostSgroupBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), hostSgroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"host_sgroup\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, hostSgroupPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from hostSgroup slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for host_sgroup")
	}

	if len(hostSgroupAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *HostSgroup) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindHostSgroup(ctx, exec, o.HostID, o.SgroupID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *HostSgroupSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := HostSgroupSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), hostSgroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"host_sgroup\".* FROM \"host_sgroup\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, hostSgroupPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in HostSgroupSlice")
	}

	*o = slice

	return nil
}

// HostSgroupExists checks if the HostSgroup row exists.
func HostSgroupExists(ctx context.Context, exec boil.ContextExecutor, hostID int64, sgroupID int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"host_sgroup\" where \"host_id\"=? AND \"sgroup_id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, hostID, sgroupID)
	}
	row := exec.QueryRowContext(ctx, sql, hostID, sgroupID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if host_sgroup exists")
	}

	return exists, nil
}

// Exists checks if the HostSgroup row exists.
func (o *HostSgroup) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return HostSgroupExists(ctx, exec, o.HostID, o.SgroupID)
}
