// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testHostSgroups(t *testing.T) {
	t.Parallel()

	query := HostSgroups()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testHostSgroupsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HostSgroup{}
	if err = randomize.Struct(seed, o, hostSgroupDBTypes, true, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := HostSgroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testHostSgroupsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HostSgroup{}
	if err = randomize.Struct(seed, o, hostSgroupDBTypes, true, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := HostSgroups().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := HostSgroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testHostSgroupsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HostSgroup{}
	if err = randomize.Struct(seed, o, hostSgroupDBTypes, true, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := HostSgroupSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := HostSgroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testHostSgroupsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HostSgroup{}
	if err = randomize.Struct(seed, o, hostSgroupDBTypes, true, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := HostSgroupExists(ctx, tx, o.HostID, o.SgroupID)
	if err != nil {
		t.Errorf("Unable to check if HostSgroup exists: %s", err)
	}
	if !e {
		t.Errorf("Expected HostSgroupExists to return true, but got false.")
	}
}

func testHostSgroupsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HostSgroup{}
	if err = randomize.Struct(seed, o, hostSgroupDBTypes, true, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	hostSgroupFound, err := FindHostSgroup(ctx, tx, o.HostID, o.SgroupID)
	if err != nil {
		t.Error(err)
	}

	if hostSgroupFound == nil {
		t.Error("want a record, got nil")
	}
}

func testHostSgroupsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HostSgroup{}
	if err = randomize.Struct(seed, o, hostSgroupDBTypes, true, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = HostSgroups().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testHostSgroupsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HostSgroup{}
	if err = randomize.Struct(seed, o, hostSgroupDBTypes, true, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := HostSgroups().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testHostSgroupsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	hostSgroupOne := &HostSgroup{}
	hostSgroupTwo := &HostSgroup{}
	if err = randomize.Struct(seed, hostSgroupOne, hostSgroupDBTypes, false, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}
	if err = randomize.Struct(seed, hostSgroupTwo, hostSgroupDBTypes, false, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = hostSgroupOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = hostSgroupTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := HostSgroups().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testHostSgroupsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	hostSgroupOne := &HostSgroup{}
	hostSgroupTwo := &HostSgroup{}
	if err = randomize.Struct(seed, hostSgroupOne, hostSgroupDBTypes, false, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}
	if err = randomize.Struct(seed, hostSgroupTwo, hostSgroupDBTypes, false, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = hostSgroupOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = hostSgroupTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := HostSgroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func hostSgroupBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *HostSgroup) error {
	*o = HostSgroup{}
	return nil
}

func hostSgroupAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *HostSgroup) error {
	*o = HostSgroup{}
	return nil
}

func hostSgroupAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *HostSgroup) error {
	*o = HostSgroup{}
	return nil
}

func hostSgroupBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *HostSgroup) error {
	*o = HostSgroup{}
	return nil
}

func hostSgroupAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *HostSgroup) error {
	*o = HostSgroup{}
	return nil
}

func hostSgroupBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *HostSgroup) error {
	*o = HostSgroup{}
	return nil
}

func hostSgroupAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *HostSgroup) error {
	*o = HostSgroup{}
	return nil
}

func hostSgroupBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *HostSgroup) error {
	*o = HostSgroup{}
	return nil
}

func hostSgroupAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *HostSgroup) error {
	*o = HostSgroup{}
	return nil
}

func testHostSgroupsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &HostSgroup{}
	o := &HostSgroup{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, hostSgroupDBTypes, false); err != nil {
		t.Errorf("Unable to randomize HostSgroup object: %s", err)
	}

	AddHostSgroupHook(boil.BeforeInsertHook, hostSgroupBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	hostSgroupBeforeInsertHooks = []HostSgroupHook{}

	AddHostSgroupHook(boil.AfterInsertHook, hostSgroupAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	hostSgroupAfterInsertHooks = []HostSgroupHook{}

	AddHostSgroupHook(boil.AfterSelectHook, hostSgroupAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	hostSgroupAfterSelectHooks = []HostSgroupHook{}

	AddHostSgroupHook(boil.BeforeUpdateHook, hostSgroupBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	hostSgroupBeforeUpdateHooks = []HostSgroupHook{}

	AddHostSgroupHook(boil.AfterUpdateHook, hostSgroupAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	hostSgroupAfterUpdateHooks = []HostSgroupHook{}

	AddHostSgroupHook(boil.BeforeDeleteHook, hostSgroupBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	hostSgroupBeforeDeleteHooks = []HostSgroupHook{}

	AddHostSgroupHook(boil.AfterDeleteHook, hostSgroupAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	hostSgroupAfterDeleteHooks = []HostSgroupHook{}

	AddHostSgroupHook(boil.BeforeUpsertHook, hostSgroupBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	hostSgroupBeforeUpsertHooks = []HostSgroupHook{}

	AddHostSgroupHook(boil.AfterUpsertHook, hostSgroupAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	hostSgroupAfterUpsertHooks = []HostSgroupHook{}
}

func testHostSgroupsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HostSgroup{}
	if err = randomize.Struct(seed, o, hostSgroupDBTypes, true, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := HostSgroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testHostSgroupsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HostSgroup{}
	if err = randomize.Struct(seed, o, hostSgroupDBTypes, true); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(hostSgroupColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := HostSgroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testHostSgroupsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HostSgroup{}
	if err = randomize.Struct(seed, o, hostSgroupDBTypes, true, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testHostSgroupsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HostSgroup{}
	if err = randomize.Struct(seed, o, hostSgroupDBTypes, true, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := HostSgroupSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testHostSgroupsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &HostSgroup{}
	if err = randomize.Struct(seed, o, hostSgroupDBTypes, true, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := HostSgroups().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	hostSgroupDBTypes = map[string]string{`HostID`: `INTEGER`, `SgroupID`: `INTEGER`}
	_                 = bytes.MinRead
)

func testHostSgroupsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(hostSgroupPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(hostSgroupAllColumns) == len(hostSgroupPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &HostSgroup{}
	if err = randomize.Struct(seed, o, hostSgroupDBTypes, true, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := HostSgroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, hostSgroupDBTypes, true, hostSgroupPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testHostSgroupsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(hostSgroupAllColumns) == len(hostSgroupPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &HostSgroup{}
	if err = randomize.Struct(seed, o, hostSgroupDBTypes, true, hostSgroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := HostSgroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, hostSgroupDBTypes, true, hostSgroupPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(hostSgroupAllColumns, hostSgroupPrimaryKeyColumns) {
		fields = hostSgroupAllColumns
	} else {
		fields = strmangle.SetComplement(
			hostSgroupAllColumns,
			hostSgroupPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := HostSgroupSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testHostSgroupsUpsert(t *testing.T) {
	t.Parallel()
	if len(hostSgroupAllColumns) == len(hostSgroupPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := HostSgroup{}
	if err = randomize.Struct(seed, &o, hostSgroupDBTypes, true); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert HostSgroup: %s", err)
	}

	count, err := HostSgroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, hostSgroupDBTypes, false, hostSgroupPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize HostSgroup struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert HostSgroup: %s", err)
	}

	count, err = HostSgroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
